spring.devtools.restart.additional-paths = files
spring.devtools.restart.exclude = static/**

spring.devtools.restart.trigger-file = c:/workspace/restart-trigger.txt

spring.freemarker.cache = false      #set false in development environment; It is false by default.

#Other cache properties

spring.thymeleaf.cache = false
spring.mustache.cache = false
spring.groovy.template.cache = false

#https://www.baeldung.com/spring-mvc-view-resolver-tutorial